// ============================================================
// 言語データ定義
// 世界15言語の詳細情報（話者数、公用語国、豆知識）
// ============================================================

export interface Language {
    id: string;
    name: { jp: string; en: string };
    nativeName: string;
    speakers: number;
    speakersFormatted: { jp: string; en: string };
    countries: string[];
    family: { jp: string; en: string };
    funFact: { jp: string; en: string };
    color: string;
}

export const languages: Language[] = [
    {
        id: 'en',
        name: { jp: '英語', en: 'English' },
        nativeName: 'English',
        speakers: 1400000000,
        speakersFormatted: { jp: '14億人', en: '1.4 billion' },
        countries: ['US', 'GB', 'AU', 'CA', 'NZ', 'IE', 'ZA', 'SG', 'IN', 'PH'],
        family: { jp: 'ゲルマン語派', en: 'Germanic' },
        funFact: {
            jp: '世界で最も学習されている第二言語。インターネット上のコンテンツの約60%は英語。',
            en: 'The most learned second language in the world. About 60% of internet content is in English.',
        },
        color: '#3B82F6',
    },
    {
        id: 'zh',
        name: { jp: '中国語', en: 'Chinese' },
        nativeName: '中文',
        speakers: 1100000000,
        speakersFormatted: { jp: '11億人', en: '1.1 billion' },
        countries: ['CN', 'TW', 'SG', 'MY'],
        family: { jp: 'シナ・チベット語族', en: 'Sino-Tibetan' },
        funFact: {
            jp: '世界で最も多くの母語話者を持つ言語。5万以上の漢字が存在する。',
            en: 'The language with the most native speakers. Over 50,000 Chinese characters exist.',
        },
        color: '#EF4444',
    },
    {
        id: 'es',
        name: { jp: 'スペイン語', en: 'Spanish' },
        nativeName: 'Español',
        speakers: 550000000,
        speakersFormatted: { jp: '5.5億人', en: '550 million' },
        countries: ['ES', 'MX', 'AR', 'CO', 'PE', 'VE', 'CL', 'EC', 'CU', 'DO'],
        family: { jp: 'ロマンス語派', en: 'Romance' },
        funFact: {
            jp: '21カ国で公用語。アメリカは世界第2位のスペイン語話者国。',
            en: 'Official in 21 countries. The USA has the second-largest Spanish-speaking population.',
        },
        color: '#F59E0B',
    },
    {
        id: 'hi',
        name: { jp: 'ヒンディー語', en: 'Hindi' },
        nativeName: 'हिन्दी',
        speakers: 600000000,
        speakersFormatted: { jp: '6億人', en: '600 million' },
        countries: ['IN', 'NP', 'FJ'],
        family: { jp: 'インド・アーリア語派', en: 'Indo-Aryan' },
        funFact: {
            jp: 'デーヴァナーガリー文字を使用。ボリウッド映画の主要言語。',
            en: 'Uses Devanagari script. The main language of Bollywood films.',
        },
        color: '#F97316',
    },
    {
        id: 'ar',
        name: { jp: 'アラビア語', en: 'Arabic' },
        nativeName: 'العربية',
        speakers: 370000000,
        speakersFormatted: { jp: '3.7億人', en: '370 million' },
        countries: ['SA', 'EG', 'AE', 'MA', 'IQ', 'SY', 'DZ', 'SD', 'JO', 'LY'],
        family: { jp: 'セム語派', en: 'Semitic' },
        funFact: {
            jp: '右から左に書く。国連公用語の一つ。',
            en: 'Written from right to left. One of the six UN official languages.',
        },
        color: '#10B981',
    },
    {
        id: 'pt',
        name: { jp: 'ポルトガル語', en: 'Portuguese' },
        nativeName: 'Português',
        speakers: 260000000,
        speakersFormatted: { jp: '2.6億人', en: '260 million' },
        countries: ['BR', 'PT', 'AO', 'MZ', 'CV'],
        family: { jp: 'ロマンス語派', en: 'Romance' },
        funFact: {
            jp: '話者の95%以上がブラジル在住。南半球で最も話されている言語。',
            en: 'Over 95% of speakers live in Brazil. Most spoken language in the Southern Hemisphere.',
        },
        color: '#22C55E',
    },
    {
        id: 'fr',
        name: { jp: 'フランス語', en: 'French' },
        nativeName: 'Français',
        speakers: 300000000,
        speakersFormatted: { jp: '3億人', en: '300 million' },
        countries: ['FR', 'CA', 'BE', 'CH', 'SN', 'CI', 'ML', 'CM', 'MG', 'HT'],
        family: { jp: 'ロマンス語派', en: 'Romance' },
        funFact: {
            jp: '外交と料理の国際語。5大陸で公用語として使用。',
            en: 'International language of diplomacy and cuisine. Official on 5 continents.',
        },
        color: '#6366F1',
    },
    {
        id: 'de',
        name: { jp: 'ドイツ語', en: 'German' },
        nativeName: 'Deutsch',
        speakers: 130000000,
        speakersFormatted: { jp: '1.3億人', en: '130 million' },
        countries: ['DE', 'AT', 'CH', 'LI', 'LU', 'BE'],
        family: { jp: 'ゲルマン語派', en: 'Germanic' },
        funFact: {
            jp: 'EU内で最も多く話されている母語。複合語が非常に長くなることで有名。',
            en: 'Most spoken native language in the EU. Famous for extremely long compound words.',
        },
        color: '#1F2937',
    },
    {
        id: 'ja',
        name: { jp: '日本語', en: 'Japanese' },
        nativeName: '日本語',
        speakers: 125000000,
        speakersFormatted: { jp: '1.25億人', en: '125 million' },
        countries: ['JP'],
        family: { jp: '日琉語族', en: 'Japonic' },
        funFact: {
            jp: '3種類の文字体系（ひらがな・カタカナ・漢字）を使用。',
            en: 'Uses three writing systems: Hiragana, Katakana, and Kanji.',
        },
        color: '#DC2626',
    },
    {
        id: 'ko',
        name: { jp: '韓国語', en: 'Korean' },
        nativeName: '한국어',
        speakers: 80000000,
        speakersFormatted: { jp: '8千万人', en: '80 million' },
        countries: ['KR', 'KP'],
        family: { jp: '孤立言語', en: 'Language isolate' },
        funFact: {
            jp: 'ハングルは15世紀に科学的に設計された文字。K-POPで世界的人気。',
            en: 'Hangul was scientifically designed in the 15th century. K-POP made it globally popular.',
        },
        color: '#0EA5E9',
    },
    {
        id: 'ru',
        name: { jp: 'ロシア語', en: 'Russian' },
        nativeName: 'Русский',
        speakers: 250000000,
        speakersFormatted: { jp: '2.5億人', en: '250 million' },
        countries: ['RU', 'BY', 'KZ', 'KG'],
        family: { jp: 'スラヴ語派', en: 'Slavic' },
        funFact: {
            jp: 'キリル文字を使用。宇宙開発の公用語の一つ。',
            en: 'Uses Cyrillic alphabet. One of the official languages of space.',
        },
        color: '#BE185D',
    },
    {
        id: 'it',
        name: { jp: 'イタリア語', en: 'Italian' },
        nativeName: 'Italiano',
        speakers: 65000000,
        speakersFormatted: { jp: '6500万人', en: '65 million' },
        countries: ['IT', 'CH', 'SM', 'VA'],
        family: { jp: 'ロマンス語派', en: 'Romance' },
        funFact: {
            jp: '音楽用語の大半はイタリア語由来。オペラの言語。',
            en: 'Most musical terms come from Italian. The language of opera.',
        },
        color: '#059669',
    },
    {
        id: 'sw',
        name: { jp: 'スワヒリ語', en: 'Swahili' },
        nativeName: 'Kiswahili',
        speakers: 100000000,
        speakersFormatted: { jp: '1億人', en: '100 million' },
        countries: ['TZ', 'KE', 'UG', 'RW', 'CD'],
        family: { jp: 'バントゥー語群', en: 'Bantu' },
        funFact: {
            jp: 'アフリカで最も広く使われている言語。「ライオン・キング」の歌詞に使用。',
            en: 'Most widely spoken language in Africa. Used in "The Lion King" songs.',
        },
        color: '#CA8A04',
    },
    {
        id: 'nl',
        name: { jp: 'オランダ語', en: 'Dutch' },
        nativeName: 'Nederlands',
        speakers: 25000000,
        speakersFormatted: { jp: '2500万人', en: '25 million' },
        countries: ['NL', 'BE', 'SR'],
        family: { jp: 'ゲルマン語派', en: 'Germanic' },
        funFact: {
            jp: '英語とドイツ語の中間的な言語。南アフリカのアフリカーンス語の親言語。',
            en: 'A bridge between English and German. Parent language of South African Afrikaans.',
        },
        color: '#EA580C',
    },
    {
        id: 'tr',
        name: { jp: 'トルコ語', en: 'Turkish' },
        nativeName: 'Türkçe',
        speakers: 80000000,
        speakersFormatted: { jp: '8千万人', en: '80 million' },
        countries: ['TR', 'CY'],
        family: { jp: 'テュルク諸語', en: 'Turkic' },
        funFact: {
            jp: '母音調和が特徴。1928年にアラビア文字からラテン文字に移行。',
            en: 'Features vowel harmony. Switched from Arabic to Latin script in 1928.',
        },
        color: '#E11D48',
    },
];

// 国コードから言語名を取得するためのマップ
export const countryNames: Record<string, { jp: string; en: string }> = {
    US: { jp: 'アメリカ', en: 'United States' },
    GB: { jp: 'イギリス', en: 'United Kingdom' },
    AU: { jp: 'オーストラリア', en: 'Australia' },
    CA: { jp: 'カナダ', en: 'Canada' },
    NZ: { jp: 'ニュージーランド', en: 'New Zealand' },
    IE: { jp: 'アイルランド', en: 'Ireland' },
    ZA: { jp: '南アフリカ', en: 'South Africa' },
    SG: { jp: 'シンガポール', en: 'Singapore' },
    IN: { jp: 'インド', en: 'India' },
    PH: { jp: 'フィリピン', en: 'Philippines' },
    CN: { jp: '中国', en: 'China' },
    TW: { jp: '台湾', en: 'Taiwan' },
    MY: { jp: 'マレーシア', en: 'Malaysia' },
    ES: { jp: 'スペイン', en: 'Spain' },
    MX: { jp: 'メキシコ', en: 'Mexico' },
    AR: { jp: 'アルゼンチン', en: 'Argentina' },
    CO: { jp: 'コロンビア', en: 'Colombia' },
    PE: { jp: 'ペルー', en: 'Peru' },
    VE: { jp: 'ベネズエラ', en: 'Venezuela' },
    CL: { jp: 'チリ', en: 'Chile' },
    EC: { jp: 'エクアドル', en: 'Ecuador' },
    CU: { jp: 'キューバ', en: 'Cuba' },
    DO: { jp: 'ドミニカ共和国', en: 'Dominican Republic' },
    NP: { jp: 'ネパール', en: 'Nepal' },
    FJ: { jp: 'フィジー', en: 'Fiji' },
    SA: { jp: 'サウジアラビア', en: 'Saudi Arabia' },
    EG: { jp: 'エジプト', en: 'Egypt' },
    AE: { jp: 'アラブ首長国連邦', en: 'UAE' },
    MA: { jp: 'モロッコ', en: 'Morocco' },
    IQ: { jp: 'イラク', en: 'Iraq' },
    SY: { jp: 'シリア', en: 'Syria' },
    DZ: { jp: 'アルジェリア', en: 'Algeria' },
    SD: { jp: 'スーダン', en: 'Sudan' },
    JO: { jp: 'ヨルダン', en: 'Jordan' },
    LY: { jp: 'リビア', en: 'Libya' },
    BR: { jp: 'ブラジル', en: 'Brazil' },
    PT: { jp: 'ポルトガル', en: 'Portugal' },
    AO: { jp: 'アンゴラ', en: 'Angola' },
    MZ: { jp: 'モザンビーク', en: 'Mozambique' },
    CV: { jp: 'カーボベルデ', en: 'Cape Verde' },
    FR: { jp: 'フランス', en: 'France' },
    BE: { jp: 'ベルギー', en: 'Belgium' },
    CH: { jp: 'スイス', en: 'Switzerland' },
    SN: { jp: 'セネガル', en: 'Senegal' },
    CI: { jp: 'コートジボワール', en: "Côte d'Ivoire" },
    ML: { jp: 'マリ', en: 'Mali' },
    CM: { jp: 'カメルーン', en: 'Cameroon' },
    MG: { jp: 'マダガスカル', en: 'Madagascar' },
    HT: { jp: 'ハイチ', en: 'Haiti' },
    DE: { jp: 'ドイツ', en: 'Germany' },
    AT: { jp: 'オーストリア', en: 'Austria' },
    LI: { jp: 'リヒテンシュタイン', en: 'Liechtenstein' },
    LU: { jp: 'ルクセンブルク', en: 'Luxembourg' },
    JP: { jp: '日本', en: 'Japan' },
    KR: { jp: '韓国', en: 'South Korea' },
    KP: { jp: '北朝鮮', en: 'North Korea' },
    RU: { jp: 'ロシア', en: 'Russia' },
    BY: { jp: 'ベラルーシ', en: 'Belarus' },
    KZ: { jp: 'カザフスタン', en: 'Kazakhstan' },
    KG: { jp: 'キルギス', en: 'Kyrgyzstan' },
    IT: { jp: 'イタリア', en: 'Italy' },
    SM: { jp: 'サンマリノ', en: 'San Marino' },
    VA: { jp: 'バチカン', en: 'Vatican' },
    TZ: { jp: 'タンザニア', en: 'Tanzania' },
    KE: { jp: 'ケニア', en: 'Kenya' },
    UG: { jp: 'ウガンダ', en: 'Uganda' },
    RW: { jp: 'ルワンダ', en: 'Rwanda' },
    CD: { jp: 'コンゴ民主共和国', en: 'DR Congo' },
    NL: { jp: 'オランダ', en: 'Netherlands' },
    SR: { jp: 'スリナム', en: 'Suriname' },
    TR: { jp: 'トルコ', en: 'Turkey' },
    CY: { jp: 'キプロス', en: 'Cyprus' },
};
